import fs from "fs-extra";
import path from "path";
import { execSync } from "child_process";
import { fileURLToPath } from "url";
import crypto from "crypto";

// Resolve current package directory (node_modules/@zozzona/js/)
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Templates folder inside package
const TEMPLATE_DIR = path.join(__dirname, "../templates");

// AES-256 key generator
function generateMapKey() {
  return crypto.randomBytes(32).toString("base64");
}

// Load pack.config.json
export function loadPackConfig() {
  const configPath = path.resolve("pack.config.json");
  if (!fs.existsSync(configPath)) return { folders: [], files: [], ignore: [] };
  return JSON.parse(fs.readFileSync(configPath, "utf-8"));
}

// ─────────────────────────────────────────────
// Ensure .env exists and contains MAP_KEY
// With full messaging + security warnings
// ─────────────────────────────────────────────
function ensureEnvFileWithMessaging() {
  const envPath = path.resolve(".env");
  let created = false;
  let addedKey = false;

  // Create .env if missing
  if (!fs.existsSync(envPath)) {
    const key = generateMapKey();
    fs.writeFileSync(
      envPath,
      `# Auto-generated by Zozzona.js\nMAP_KEY=${key}\n`,
      "utf-8"
    );
    created = true;
    console.log(`✔ Created .env at: ${envPath}`);
  } else {
    // .env exists — ensure MAP_KEY is present
    const content = fs.readFileSync(envPath, "utf-8");
    if (!content.includes("MAP_KEY=")) {
      const key = generateMapKey();
      fs.appendFileSync(envPath, `\nMAP_KEY=${key}\n`);
      addedKey = true;
      console.log(`✔ Added MAP_KEY to existing .env: ${envPath}`);
    } else {
      console.log(`ℹ Using existing MAP_KEY from: ${envPath}`);
    }
  }

  // Show resulting .env content
  const final = fs.readFileSync(envPath, "utf-8");
  console.log("\n━━━━━━━━━━━━━━━━━━━━");
  console.log("📄 Your .env now contains:\n");
  console.log(final.trim());
  console.log("━━━━━━━━━━━━━━━━━━━━\n");

  console.log("⚠ IMPORTANT:");
  console.log("• Keep your MAP_KEY safe — it decrypts your source code.");
  console.log("• NEVER commit .env to Git (add it to .gitignore).");
  console.log("• If you lose MAP_KEY, you cannot unpack encrypted files.\n");
}

// ─────────────────────────────────────────────
// Create pack.config.json if missing
// ─────────────────────────────────────────────
function ensurePackConfig() {
  const dest = "pack.config.json";
  if (!fs.existsSync(dest)) {
    fs.copyFileSync(path.join(TEMPLATE_DIR, "pack.config.json"), dest);
    console.log("✔ Created pack.config.json");
  }
}

// Inject scripts into user's package.json
function ensurePackageScripts() {
  const pkgPath = path.resolve("package.json");
  if (!fs.existsSync(pkgPath)) {
    console.error("❌ No package.json found in this project.");
    process.exit(1);
  }

  const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
  pkg.scripts = pkg.scripts || {};

  let changed = false;

  const required = {
    obfuscate: "node node_modules/@zozzona/js/src/obfuscate.js obfuscate",
    deobfuscate: "node node_modules/@zozzona/js/src/obfuscate.js deobfuscate",
    minify: "node node_modules/@zozzona/js/src/minify.js minify",
    deminify: "node node_modules/@zozzona/js/src/minify.js restore",
    pack: "zozzona pack",
    unpack: "zozzona unpack"
  };

  for (const [key, value] of Object.entries(required)) {
    if (!pkg.scripts[key]) {
      pkg.scripts[key] = value;
      changed = true;
    }
  }

  if (changed) {
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));
    console.log("✔ Added zozzona scripts to package.json");
  }
}

// ─────────────────────────────────────────────
// Install Husky automatically
// ─────────────────────────────────────────────
function installHusky() {
  console.log("📦 Installing Husky...");

  // Install husky (automated)
  execSync("npm install husky --save-dev", { stdio: "inherit" });

  console.log("🔧 Running husky install...");
  execSync("npx husky install", { stdio: "inherit" });

  fs.mkdirpSync(".husky");

  const pre = path.join(".husky", "pre-commit");
  const post = path.join(".husky", "post-commit");

  fs.copyFileSync(path.join(TEMPLATE_DIR, "husky-pre-commit.sh"), pre);
  fs.copyFileSync(path.join(TEMPLATE_DIR, "husky-post-commit.sh"), post);

  fs.chmodSync(pre, 0o755);
  fs.chmodSync(post, 0o755);

  console.log("✔ Husky hooks installed and activated");
}

// ─────────────────────────────────────────────
// CLI Router
// ─────────────────────────────────────────────
export function runCLI() {
  const cmd = process.argv[2];

  if (!cmd || ["help", "-h", "--help"].includes(cmd)) {
    console.log(`
Zozzona.js CLI
--------------
Usage:
  zozzona init       Setup config + hooks + env + scripts
  zozzona pack       Obfuscate + minify + encrypt
  zozzona unpack     Decrypt + restore
  zozzona version    Show installed version
`);
    return;
  }

  if (cmd === "version") {
    const pkg = JSON.parse(
      fs.readFileSync(path.join(__dirname, "../package.json"), "utf-8")
    );
    console.log(pkg.version);
    return;
  }

  if (cmd === "init") {
    ensureEnvFileWithMessaging();
    ensurePackConfig();
    ensurePackageScripts();
    installHusky();
    return;
  }

  if (cmd === "pack") {
    const runner = path.join(__dirname, "runner.js");
    execSync(`node "${runner}" pack`, { stdio: "inherit" });
    return;
  }

  if (cmd === "unpack") {
    const runner = path.join(__dirname, "runner.js");
    execSync(`node "${runner}" unpack`, { stdio: "inherit" });
    return;
  }

  console.error(`Unknown command: ${cmd}`);
  process.exit(1);
}
